blueprint:
  name: EV Charger Load Balancing
  description: >
    Dynamically adjusts the charging current of a single EV charger so that
    the total household current draw stays within the configured service limit.
    Whenever the power meter changes, the automation computes the available
    current (service limit minus non-EV load) and calls a user-supplied script
    to set the charger's target current.  If the available current falls below
    the minimum charging threshold the charger is stopped.

    Note: For persistent sensors, multi-charger fairness, or a better
    configuration UI, consider the AppDaemon app (apps/ev_lb/ev_lb.py) or a
    custom HACS integration instead of this blueprint.
  domain: automation
  author: alexisml
  homeassistant:
    min_version: "2023.6.0"

  input:
    power_sensor:
      name: Household power sensor
      description: >
        Sensor reporting current total household power draw in Watts,
        **including** any active EV charging (e.g. sensor.house_power_w).
      selector:
        entity:
          domain: sensor
          device_class: power

    voltage_v:
      name: Supply voltage (V)
      description: Nominal supply voltage in Volts.
      default: 230
      selector:
        number:
          min: 100
          max: 480
          unit_of_measurement: V
          mode: box

    max_service_current_a:
      name: Maximum service current (A)
      description: >
        Whole-house breaker / service rating in Amps.  The automation will
        never allow total household draw to exceed this value.
      selector:
        entity:
          domain: input_number

    max_charging_current_a:
      name: Charger maximum current (A)
      description: >
        Per-charger maximum charging current in Amps.  Use an input_number
        helper so the limit can be changed at runtime.
      selector:
        entity:
          domain: input_number

    min_charging_current_a:
      name: Minimum charging current before shutdown (A)
      description: >
        If the available current drops below this value the automation will
        stop the charger rather than set an impractically low current.
        Default 6 A (IEC 61851 minimum for AC charging).
      default: 6
      selector:
        number:
          min: 1
          max: 32
          unit_of_measurement: A
          mode: box

    lb_enabled:
      name: Load balancing enabled toggle
      description: >
        input_boolean that enables or disables dynamic load balancing.
        When off, the automation does nothing.
      selector:
        entity:
          domain: input_boolean

    set_current_service:
      name: Set current script / service
      description: >
        Script or service to call when setting the charger's target current.
        The script receives:
          charger_id: the entity_id of the charger entity (same as the
                      selector below)
          current_a:  target current in Amps (float)
      selector:
        entity:
          domain: script

    charger_entity:
      name: Charger entity
      description: >
        The entity_id used to identify the charger when calling the scripts
        above (e.g. the OCPP charger entity created by lbbrhzn/ocpp).
      selector:
        entity: {}

    stop_charging_service:
      name: Stop charging script / service (optional)
      description: >
        Script to call when charging must be stopped because available
        current is below the minimum threshold.
        Leave empty to skip.  The script receives charger_id.
      default: ""
      selector:
        entity:
          domain: script

trigger:
  - platform: state
    entity_id: !input power_sensor

condition:
  - condition: state
    entity_id: !input lb_enabled
    state: "on"

  - condition: template
    value_template: >
      {{ trigger.to_state.state not in ['unavailable', 'unknown'] }}

action:
  - variables:
      voltage_v: !input voltage_v
      max_service_a: "{{ states(!input max_service_current_a) | float(0) }}"
      max_charger_a: "{{ states(!input max_charging_current_a) | float(0) }}"
      min_current_a: !input min_charging_current_a
      house_power_w: "{{ trigger.to_state.state | float(0) }}"
      charger_entity: !input charger_entity
      set_current_svc: !input set_current_service
      stop_charging_svc: !input stop_charging_service

      # Compute available current.
      # We do not track the live EV draw in the blueprint (no persistent state),
      # so we use the conservative formula: assume all house load is non-EV.
      # This is safe — it will never exceed the service limit.
      available_a: >
        {{ [max_service_a - (house_power_w / voltage_v), 0] | max }}

      target_a: >
        {% set raw = [available_a, max_charger_a] | min %}
        {% set stepped = raw | int %}
        {{ stepped }}

  - choose:
      # --- Stop charging: available current is below minimum ---
      - conditions:
          - condition: template
            value_template: "{{ target_a | float < min_current_a | float }}"
        sequence:
          - condition: template
            value_template: "{{ stop_charging_svc != '' }}"
          - service: "{{ stop_charging_svc }}"
            data:
              charger_id: "{{ charger_entity }}"

      # --- Set current ---
      - conditions:
          - condition: template
            value_template: "{{ target_a | float >= min_current_a | float }}"
        sequence:
          - service: "{{ set_current_svc }}"
            data:
              charger_id: "{{ charger_entity }}"
              current_a: "{{ target_a | float }}"

mode: single
max_exceeded: silent
